safe: true
lsi: false
pygments: true
source: .
permalink: /:title/
baseurl: "/"
url: http://exotericgroup.github.io
exclude:
- ".*"
- "*.md"
- "Gemfile*"
- "CNAME"

owner:
  name: Exoteric Growth
  contact: mailto:tyler@exotericgrowth.com
  website: http://www.exotericgrowth.com
  github: https://github.com/exotericgroup
  facebook: https://www.facebook.com/exotericgrowth

license:
  name: CC-BY-SA
  url: http://creativecommons.org/licenses/by-sa/3.0/

analytics:
  provider: google
  google:
    id: 'UA-62764192-1', 'auto');
  ga('send', 'pageview');

</script>
